# build stage
FROM node:12-alpine3.11 as build

WORKDIR /usr/src/app

COPY . ./
RUN npm install
RUN npm run-script build --quiet

# prod stage
FROM node:12-alpine3.11

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules node_modules/
COPY --from=build /usr/src/app/dist .